replicaCount: 1

server:
  image: ahmadibraspectrocloud/count-server:latest
  hostname: count-grpc-server
  port: 3005

client:
  image: ahmadibraspectrocloud/count-client:latest
  hostname: count-grpc-client
