apiVersion: apps/v1
kind: Deployment
metadata:
  name: count-client
  labels:
    app: {{ .Values.client.hostname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.client.hostname }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.hostname }}
    spec:
      containers:
        - name: {{ .Values.client.hostname }}
          image: "{{ .Values.client.image }}"
          env:
          - name: PORT
            value: "{{ .Values.server.port }}"
          - name: HOST
            value: "{{ .Values.server.hostname }}"
