apiVersion: apps/v1
kind: Deployment
metadata:
  name: count-server
  labels:
    app: {{ .Values.server.hostname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.server.hostname }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.hostname }}
    spec:
      containers:
        - name: {{ .Values.server.hostname }}
          image: "{{ .Values.server.image }}"
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
          env:
          - name: PORT
            value: "{{ .Values.server.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.hostname }}
spec:
  selector:
    app: {{ .Values.server.hostname }}
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
